package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * AllCateInfoId generated by hbm2java
 */
public class AllCateInfoId implements java.io.Serializable {

	private String status;
	private String subtitle;
	private String title;
	private String createdAt;
	private String updatedAt;
	private Integer id;
	private String coverImageUrl;
	private String bannerImageUrl;
	private Integer postsCount;
	private String createdAt_1;

	public AllCateInfoId() {
	}

	public AllCateInfoId(String status, String subtitle, String title, String createdAt, String updatedAt, Integer id,
			String coverImageUrl, String bannerImageUrl, Integer postsCount, String createdAt_1) {
		this.status = status;
		this.subtitle = subtitle;
		this.title = title;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.id = id;
		this.coverImageUrl = coverImageUrl;
		this.bannerImageUrl = bannerImageUrl;
		this.postsCount = postsCount;
		this.createdAt_1 = createdAt_1;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getSubtitle() {
		return this.subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	public String getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(String updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCoverImageUrl() {
		return this.coverImageUrl;
	}

	public void setCoverImageUrl(String coverImageUrl) {
		this.coverImageUrl = coverImageUrl;
	}

	public String getBannerImageUrl() {
		return this.bannerImageUrl;
	}

	public void setBannerImageUrl(String bannerImageUrl) {
		this.bannerImageUrl = bannerImageUrl;
	}

	public Integer getPostsCount() {
		return this.postsCount;
	}

	public void setPostsCount(Integer postsCount) {
		this.postsCount = postsCount;
	}

	public String getCreatedAt_1() {
		return this.createdAt_1;
	}

	public void setCreatedAt_1(String createdAt_1) {
		this.createdAt_1 = createdAt_1;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AllCateInfoId))
			return false;
		AllCateInfoId castOther = (AllCateInfoId) other;

		return ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
				&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getSubtitle() == castOther.getSubtitle()) || (this.getSubtitle() != null
						&& castOther.getSubtitle() != null && this.getSubtitle().equals(castOther.getSubtitle())))
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getCoverImageUrl() == castOther.getCoverImageUrl())
						|| (this.getCoverImageUrl() != null && castOther.getCoverImageUrl() != null
								&& this.getCoverImageUrl().equals(castOther.getCoverImageUrl())))
				&& ((this.getBannerImageUrl() == castOther.getBannerImageUrl())
						|| (this.getBannerImageUrl() != null && castOther.getBannerImageUrl() != null
								&& this.getBannerImageUrl().equals(castOther.getBannerImageUrl())))
				&& ((this.getPostsCount() == castOther.getPostsCount()) || (this.getPostsCount() != null
						&& castOther.getPostsCount() != null && this.getPostsCount().equals(castOther.getPostsCount())))
				&& ((this.getCreatedAt_1() == castOther.getCreatedAt_1())
						|| (this.getCreatedAt_1() != null && castOther.getCreatedAt_1() != null
								&& this.getCreatedAt_1().equals(castOther.getCreatedAt_1())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getSubtitle() == null ? 0 : this.getSubtitle().hashCode());
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getCoverImageUrl() == null ? 0 : this.getCoverImageUrl().hashCode());
		result = 37 * result + (getBannerImageUrl() == null ? 0 : this.getBannerImageUrl().hashCode());
		result = 37 * result + (getPostsCount() == null ? 0 : this.getPostsCount().hashCode());
		result = 37 * result + (getCreatedAt_1() == null ? 0 : this.getCreatedAt_1().hashCode());
		return result;
	}

}
