package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * AllCateInfo generated by hbm2java
 */
public class AllCateInfo implements java.io.Serializable {

	private AllCateInfoId id;

	public AllCateInfo() {
	}

	public AllCateInfo(AllCateInfoId id) {
		this.id = id;
	}

	public AllCateInfoId getId() {
		return this.id;
	}

	public void setId(AllCateInfoId id) {
		this.id = id;
	}

}
