package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * CatePageInfo generated by hbm2java
 */
public class CatePageInfo implements java.io.Serializable {

	private CatePageInfoId id;

	public CatePageInfo() {
	}

	public CatePageInfo(CatePageInfoId id) {
		this.id = id;
	}

	public CatePageInfoId getId() {
		return this.id;
	}

	public void setId(CatePageInfoId id) {
		this.id = id;
	}

}
