package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * FavoListsInfoId generated by hbm2java
 */
public class FavoListsInfoId implements java.io.Serializable {

	private Integer itemsCount;
	private Integer userId;
	private String description;
	private String url;
	private String createdAt;
	private String updatedAt;
	private String publicc;
	private String headImageUrl;
	private String coverImageUrl;
	private Integer id;
	private String name;

	public FavoListsInfoId() {
	}

	public FavoListsInfoId(Integer itemsCount, Integer userId, String description, String url, String createdAt,
			String updatedAt, String publicc, String headImageUrl, String coverImageUrl, Integer id, String name) {
		this.itemsCount = itemsCount;
		this.userId = userId;
		this.description = description;
		this.url = url;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.publicc = publicc;
		this.headImageUrl = headImageUrl;
		this.coverImageUrl = coverImageUrl;
		this.id = id;
		this.name = name;
	}

	public Integer getItemsCount() {
		return this.itemsCount;
	}

	public void setItemsCount(Integer itemsCount) {
		this.itemsCount = itemsCount;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	public String getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(String updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getPublicc() {
		return this.publicc;
	}

	public void setPublicc(String publicc) {
		this.publicc = publicc;
	}

	public String getHeadImageUrl() {
		return this.headImageUrl;
	}

	public void setHeadImageUrl(String headImageUrl) {
		this.headImageUrl = headImageUrl;
	}

	public String getCoverImageUrl() {
		return this.coverImageUrl;
	}

	public void setCoverImageUrl(String coverImageUrl) {
		this.coverImageUrl = coverImageUrl;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoListsInfoId))
			return false;
		FavoListsInfoId castOther = (FavoListsInfoId) other;

		return ((this.getItemsCount() == castOther.getItemsCount()) || (this.getItemsCount() != null
				&& castOther.getItemsCount() != null && this.getItemsCount().equals(castOther.getItemsCount())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null && castOther.getUrl() != null
						&& this.getUrl().equals(castOther.getUrl())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getPublicc() == castOther.getPublicc()) || (this.getPublicc() != null
						&& castOther.getPublicc() != null && this.getPublicc().equals(castOther.getPublicc())))
				&& ((this.getHeadImageUrl() == castOther.getHeadImageUrl())
						|| (this.getHeadImageUrl() != null && castOther.getHeadImageUrl() != null
								&& this.getHeadImageUrl().equals(castOther.getHeadImageUrl())))
				&& ((this.getCoverImageUrl() == castOther.getCoverImageUrl())
						|| (this.getCoverImageUrl() != null && castOther.getCoverImageUrl() != null
								&& this.getCoverImageUrl().equals(castOther.getCoverImageUrl())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getItemsCount() == null ? 0 : this.getItemsCount().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getPublicc() == null ? 0 : this.getPublicc().hashCode());
		result = 37 * result + (getHeadImageUrl() == null ? 0 : this.getHeadImageUrl().hashCode());
		result = 37 * result + (getCoverImageUrl() == null ? 0 : this.getCoverImageUrl().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
