package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * FavoListsInfo generated by hbm2java
 */
public class FavoListsInfo implements java.io.Serializable {

	private FavoListsInfoId id;

	public FavoListsInfo() {
	}

	public FavoListsInfo(FavoListsInfoId id) {
		this.id = id;
	}

	public FavoListsInfoId getId() {
		return this.id;
	}

	public void setId(FavoListsInfoId id) {
		this.id = id;
	}

}
