package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * FirstPageCateInfoId generated by hbm2java
 */
public class FirstPageCateInfoId implements java.io.Serializable {

	private String editable;
	private Integer id;
	private String name;

	public FirstPageCateInfoId() {
	}

	public FirstPageCateInfoId(String editable, Integer id, String name) {
		this.editable = editable;
		this.id = id;
		this.name = name;
	}

	public String getEditable() {
		return this.editable;
	}

	public void setEditable(String editable) {
		this.editable = editable;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FirstPageCateInfoId))
			return false;
		FirstPageCateInfoId castOther = (FirstPageCateInfoId) other;

		return ((this.getEditable() == castOther.getEditable()) || (this.getEditable() != null
				&& castOther.getEditable() != null && this.getEditable().equals(castOther.getEditable())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEditable() == null ? 0 : this.getEditable().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
