package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * FirstPageAdsInfo generated by hbm2java
 */
public class FirstPageAdsInfo implements java.io.Serializable {

	private FirstPageAdsInfoId id;

	public FirstPageAdsInfo() {
	}

	public FirstPageAdsInfo(FirstPageAdsInfoId id) {
		this.id = id;
	}

	public FirstPageAdsInfoId getId() {
		return this.id;
	}

	public void setId(FirstPageAdsInfoId id) {
		this.id = id;
	}

}
