package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * FirstPageCateInfo generated by hbm2java
 */
public class FirstPageCateInfo implements java.io.Serializable {

	private FirstPageCateInfoId id;

	public FirstPageCateInfo() {
	}

	public FirstPageCateInfo(FirstPageCateInfoId id) {
		this.id = id;
	}

	public FirstPageCateInfoId getId() {
		return this.id;
	}

	public void setId(FirstPageCateInfoId id) {
		this.id = id;
	}

}
