package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * FirstPageAdsInfoId generated by hbm2java
 */
public class FirstPageAdsInfoId implements java.io.Serializable {

	private String status;
	private String targetUrl;
	private String target;
	private String targetId;
	private String order;
	private String imageUrl;
	private String type;
	private Integer id;
	private String channel;

	public FirstPageAdsInfoId() {
	}

	public FirstPageAdsInfoId(String status, String targetUrl, String target, String targetId, String order,
			String imageUrl, String type, Integer id, String channel) {
		this.status = status;
		this.targetUrl = targetUrl;
		this.target = target;
		this.targetId = targetId;
		this.order = order;
		this.imageUrl = imageUrl;
		this.type = type;
		this.id = id;
		this.channel = channel;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTargetUrl() {
		return this.targetUrl;
	}

	public void setTargetUrl(String targetUrl) {
		this.targetUrl = targetUrl;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getTargetId() {
		return this.targetId;
	}

	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}

	public String getOrder() {
		return this.order;
	}

	public void setOrder(String order) {
		this.order = order;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FirstPageAdsInfoId))
			return false;
		FirstPageAdsInfoId castOther = (FirstPageAdsInfoId) other;

		return ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
				&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getTargetUrl() == castOther.getTargetUrl()) || (this.getTargetUrl() != null
						&& castOther.getTargetUrl() != null && this.getTargetUrl().equals(castOther.getTargetUrl())))
				&& ((this.getTarget() == castOther.getTarget()) || (this.getTarget() != null
						&& castOther.getTarget() != null && this.getTarget().equals(castOther.getTarget())))
				&& ((this.getTargetId() == castOther.getTargetId()) || (this.getTargetId() != null
						&& castOther.getTargetId() != null && this.getTargetId().equals(castOther.getTargetId())))
				&& ((this.getOrder() == castOther.getOrder()) || (this.getOrder() != null
						&& castOther.getOrder() != null && this.getOrder().equals(castOther.getOrder())))
				&& ((this.getImageUrl() == castOther.getImageUrl()) || (this.getImageUrl() != null
						&& castOther.getImageUrl() != null && this.getImageUrl().equals(castOther.getImageUrl())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getChannel() == castOther.getChannel()) || (this.getChannel() != null
						&& castOther.getChannel() != null && this.getChannel().equals(castOther.getChannel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getTargetUrl() == null ? 0 : this.getTargetUrl().hashCode());
		result = 37 * result + (getTarget() == null ? 0 : this.getTarget().hashCode());
		result = 37 * result + (getTargetId() == null ? 0 : this.getTargetId().hashCode());
		result = 37 * result + (getOrder() == null ? 0 : this.getOrder().hashCode());
		result = 37 * result + (getImageUrl() == null ? 0 : this.getImageUrl().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getChannel() == null ? 0 : this.getChannel().hashCode());
		return result;
	}

}
