package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * ListPageInfoId generated by hbm2java
 */
public class ListPageInfoId implements java.io.Serializable {

	private String status;
	private String liked;
	private String template;
	private String title;
	private String url;
	private String type;
	private String createdAt;
	private String labels;
	private String updatedAt;
	private String contentUrl;
	private String publishedAt;
	private String shortTitle;
	private String coverImageUrl;
	private String editorId;
	private Integer id;
	private String shareMsg;
	private Integer likesCount;

	public ListPageInfoId() {
	}

	public ListPageInfoId(String status, String liked, String template, String title, String url, String type,
			String createdAt, String labels, String updatedAt, String contentUrl, String publishedAt, String shortTitle,
			String coverImageUrl, String editorId, Integer id, String shareMsg, Integer likesCount) {
		this.status = status;
		this.liked = liked;
		this.template = template;
		this.title = title;
		this.url = url;
		this.type = type;
		this.createdAt = createdAt;
		this.labels = labels;
		this.updatedAt = updatedAt;
		this.contentUrl = contentUrl;
		this.publishedAt = publishedAt;
		this.shortTitle = shortTitle;
		this.coverImageUrl = coverImageUrl;
		this.editorId = editorId;
		this.id = id;
		this.shareMsg = shareMsg;
		this.likesCount = likesCount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getLiked() {
		return this.liked;
	}

	public void setLiked(String liked) {
		this.liked = liked;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	public String getLabels() {
		return this.labels;
	}

	public void setLabels(String labels) {
		this.labels = labels;
	}

	public String getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(String updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getContentUrl() {
		return this.contentUrl;
	}

	public void setContentUrl(String contentUrl) {
		this.contentUrl = contentUrl;
	}

	public String getPublishedAt() {
		return this.publishedAt;
	}

	public void setPublishedAt(String publishedAt) {
		this.publishedAt = publishedAt;
	}

	public String getShortTitle() {
		return this.shortTitle;
	}

	public void setShortTitle(String shortTitle) {
		this.shortTitle = shortTitle;
	}

	public String getCoverImageUrl() {
		return this.coverImageUrl;
	}

	public void setCoverImageUrl(String coverImageUrl) {
		this.coverImageUrl = coverImageUrl;
	}

	public String getEditorId() {
		return this.editorId;
	}

	public void setEditorId(String editorId) {
		this.editorId = editorId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getShareMsg() {
		return this.shareMsg;
	}

	public void setShareMsg(String shareMsg) {
		this.shareMsg = shareMsg;
	}

	public Integer getLikesCount() {
		return this.likesCount;
	}

	public void setLikesCount(Integer likesCount) {
		this.likesCount = likesCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ListPageInfoId))
			return false;
		ListPageInfoId castOther = (ListPageInfoId) other;

		return ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
				&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getLiked() == castOther.getLiked()) || (this.getLiked() != null
						&& castOther.getLiked() != null && this.getLiked().equals(castOther.getLiked())))
				&& ((this.getTemplate() == castOther.getTemplate()) || (this.getTemplate() != null
						&& castOther.getTemplate() != null && this.getTemplate().equals(castOther.getTemplate())))
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null && castOther.getUrl() != null
						&& this.getUrl().equals(castOther.getUrl())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getLabels() == castOther.getLabels()) || (this.getLabels() != null
						&& castOther.getLabels() != null && this.getLabels().equals(castOther.getLabels())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getContentUrl() == castOther.getContentUrl()) || (this.getContentUrl() != null
						&& castOther.getContentUrl() != null && this.getContentUrl().equals(castOther.getContentUrl())))
				&& ((this.getPublishedAt() == castOther.getPublishedAt())
						|| (this.getPublishedAt() != null && castOther.getPublishedAt() != null
								&& this.getPublishedAt().equals(castOther.getPublishedAt())))
				&& ((this.getShortTitle() == castOther.getShortTitle()) || (this.getShortTitle() != null
						&& castOther.getShortTitle() != null && this.getShortTitle().equals(castOther.getShortTitle())))
				&& ((this.getCoverImageUrl() == castOther.getCoverImageUrl())
						|| (this.getCoverImageUrl() != null && castOther.getCoverImageUrl() != null
								&& this.getCoverImageUrl().equals(castOther.getCoverImageUrl())))
				&& ((this.getEditorId() == castOther.getEditorId()) || (this.getEditorId() != null
						&& castOther.getEditorId() != null && this.getEditorId().equals(castOther.getEditorId())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getShareMsg() == castOther.getShareMsg()) || (this.getShareMsg() != null
						&& castOther.getShareMsg() != null && this.getShareMsg().equals(castOther.getShareMsg())))
				&& ((this.getLikesCount() == castOther.getLikesCount())
						|| (this.getLikesCount() != null && castOther.getLikesCount() != null
								&& this.getLikesCount().equals(castOther.getLikesCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getLiked() == null ? 0 : this.getLiked().hashCode());
		result = 37 * result + (getTemplate() == null ? 0 : this.getTemplate().hashCode());
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getLabels() == null ? 0 : this.getLabels().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getContentUrl() == null ? 0 : this.getContentUrl().hashCode());
		result = 37 * result + (getPublishedAt() == null ? 0 : this.getPublishedAt().hashCode());
		result = 37 * result + (getShortTitle() == null ? 0 : this.getShortTitle().hashCode());
		result = 37 * result + (getCoverImageUrl() == null ? 0 : this.getCoverImageUrl().hashCode());
		result = 37 * result + (getEditorId() == null ? 0 : this.getEditorId().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getShareMsg() == null ? 0 : this.getShareMsg().hashCode());
		result = 37 * result + (getLikesCount() == null ? 0 : this.getLikesCount().hashCode());
		return result;
	}

}
