package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * ListPageInfo generated by hbm2java
 */
public class ListPageInfo implements java.io.Serializable {

	private ListPageInfoId id;

	public ListPageInfo() {
	}

	public ListPageInfo(ListPageInfoId id) {
		this.id = id;
	}

	public ListPageInfoId getId() {
		return this.id;
	}

	public void setId(ListPageInfoId id) {
		this.id = id;
	}

}
