package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * MainMenuInfo generated by hbm2java
 */
public class MainMenuInfo implements java.io.Serializable {

	private MainMenuInfoId id;

	public MainMenuInfo() {
	}

	public MainMenuInfo(MainMenuInfoId id) {
		this.id = id;
	}

	public MainMenuInfoId getId() {
		return this.id;
	}

	public void setId(MainMenuInfoId id) {
		this.id = id;
	}

}
