package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * MainMenuInfoId generated by hbm2java
 */
public class MainMenuInfoId implements java.io.Serializable {

	private String coverImageUrl;
	private String contentUrl;
	private String createdAt;
	private String editorId;
	private String id;
	private String labels;
	private String liked;
	private String likesCount;
	private String publishedAt;
	private String shareMsg;
	private String status;
	private String shortTitle;
	private String template;
	private String type;
	private String title;
	private String updatedAt;
	private String url;

	public MainMenuInfoId() {
	}

	public MainMenuInfoId(String coverImageUrl, String contentUrl, String createdAt, String editorId, String id,
			String labels, String liked, String likesCount, String publishedAt, String shareMsg, String status,
			String shortTitle, String template, String type, String title, String updatedAt, String url) {
		this.coverImageUrl = coverImageUrl;
		this.contentUrl = contentUrl;
		this.createdAt = createdAt;
		this.editorId = editorId;
		this.id = id;
		this.labels = labels;
		this.liked = liked;
		this.likesCount = likesCount;
		this.publishedAt = publishedAt;
		this.shareMsg = shareMsg;
		this.status = status;
		this.shortTitle = shortTitle;
		this.template = template;
		this.type = type;
		this.title = title;
		this.updatedAt = updatedAt;
		this.url = url;
	}

	public String getCoverImageUrl() {
		return this.coverImageUrl;
	}

	public void setCoverImageUrl(String coverImageUrl) {
		this.coverImageUrl = coverImageUrl;
	}

	public String getContentUrl() {
		return this.contentUrl;
	}

	public void setContentUrl(String contentUrl) {
		this.contentUrl = contentUrl;
	}

	public String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	public String getEditorId() {
		return this.editorId;
	}

	public void setEditorId(String editorId) {
		this.editorId = editorId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLabels() {
		return this.labels;
	}

	public void setLabels(String labels) {
		this.labels = labels;
	}

	public String getLiked() {
		return this.liked;
	}

	public void setLiked(String liked) {
		this.liked = liked;
	}

	public String getLikesCount() {
		return this.likesCount;
	}

	public void setLikesCount(String likesCount) {
		this.likesCount = likesCount;
	}

	public String getPublishedAt() {
		return this.publishedAt;
	}

	public void setPublishedAt(String publishedAt) {
		this.publishedAt = publishedAt;
	}

	public String getShareMsg() {
		return this.shareMsg;
	}

	public void setShareMsg(String shareMsg) {
		this.shareMsg = shareMsg;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getShortTitle() {
		return this.shortTitle;
	}

	public void setShortTitle(String shortTitle) {
		this.shortTitle = shortTitle;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(String updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MainMenuInfoId))
			return false;
		MainMenuInfoId castOther = (MainMenuInfoId) other;

		return ((this.getCoverImageUrl() == castOther.getCoverImageUrl())
				|| (this.getCoverImageUrl() != null && castOther.getCoverImageUrl() != null
						&& this.getCoverImageUrl().equals(castOther.getCoverImageUrl())))
				&& ((this.getContentUrl() == castOther.getContentUrl()) || (this.getContentUrl() != null
						&& castOther.getContentUrl() != null && this.getContentUrl().equals(castOther.getContentUrl())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getEditorId() == castOther.getEditorId()) || (this.getEditorId() != null
						&& castOther.getEditorId() != null && this.getEditorId().equals(castOther.getEditorId())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getLabels() == castOther.getLabels()) || (this.getLabels() != null
						&& castOther.getLabels() != null && this.getLabels().equals(castOther.getLabels())))
				&& ((this.getLiked() == castOther.getLiked()) || (this.getLiked() != null
						&& castOther.getLiked() != null && this.getLiked().equals(castOther.getLiked())))
				&& ((this.getLikesCount() == castOther.getLikesCount()) || (this.getLikesCount() != null
						&& castOther.getLikesCount() != null && this.getLikesCount().equals(castOther.getLikesCount())))
				&& ((this.getPublishedAt() == castOther.getPublishedAt())
						|| (this.getPublishedAt() != null && castOther.getPublishedAt() != null
								&& this.getPublishedAt().equals(castOther.getPublishedAt())))
				&& ((this.getShareMsg() == castOther.getShareMsg()) || (this.getShareMsg() != null
						&& castOther.getShareMsg() != null && this.getShareMsg().equals(castOther.getShareMsg())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getShortTitle() == castOther.getShortTitle()) || (this.getShortTitle() != null
						&& castOther.getShortTitle() != null && this.getShortTitle().equals(castOther.getShortTitle())))
				&& ((this.getTemplate() == castOther.getTemplate()) || (this.getTemplate() != null
						&& castOther.getTemplate() != null && this.getTemplate().equals(castOther.getTemplate())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null && castOther.getUrl() != null
						&& this.getUrl().equals(castOther.getUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoverImageUrl() == null ? 0 : this.getCoverImageUrl().hashCode());
		result = 37 * result + (getContentUrl() == null ? 0 : this.getContentUrl().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getEditorId() == null ? 0 : this.getEditorId().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getLabels() == null ? 0 : this.getLabels().hashCode());
		result = 37 * result + (getLiked() == null ? 0 : this.getLiked().hashCode());
		result = 37 * result + (getLikesCount() == null ? 0 : this.getLikesCount().hashCode());
		result = 37 * result + (getPublishedAt() == null ? 0 : this.getPublishedAt().hashCode());
		result = 37 * result + (getShareMsg() == null ? 0 : this.getShareMsg().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getShortTitle() == null ? 0 : this.getShortTitle().hashCode());
		result = 37 * result + (getTemplate() == null ? 0 : this.getTemplate().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getUrl() == null ? 0 : this.getUrl().hashCode());
		return result;
	}

}
