package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * MessageInfo generated by hbm2java
 */
public class MessageInfo implements java.io.Serializable {

	private MessageInfoId id;
	private Integer messageTypeId;
	private Integer messageInfoId;
	private Integer messageGeoId;
	private String messageStatus;
	private Date messageCreateDate;
	private Date messageLastUpdateDate;

	public MessageInfo() {
	}

	public MessageInfo(MessageInfoId id) {
		this.id = id;
	}

	public MessageInfo(MessageInfoId id, Integer messageTypeId, Integer messageInfoId, Integer messageGeoId,
			String messageStatus, Date messageCreateDate, Date messageLastUpdateDate) {
		this.id = id;
		this.messageTypeId = messageTypeId;
		this.messageInfoId = messageInfoId;
		this.messageGeoId = messageGeoId;
		this.messageStatus = messageStatus;
		this.messageCreateDate = messageCreateDate;
		this.messageLastUpdateDate = messageLastUpdateDate;
	}

	public MessageInfoId getId() {
		return this.id;
	}

	public void setId(MessageInfoId id) {
		this.id = id;
	}

	public Integer getMessageTypeId() {
		return this.messageTypeId;
	}

	public void setMessageTypeId(Integer messageTypeId) {
		this.messageTypeId = messageTypeId;
	}

	public Integer getMessageInfoId() {
		return this.messageInfoId;
	}

	public void setMessageInfoId(Integer messageInfoId) {
		this.messageInfoId = messageInfoId;
	}

	public Integer getMessageGeoId() {
		return this.messageGeoId;
	}

	public void setMessageGeoId(Integer messageGeoId) {
		this.messageGeoId = messageGeoId;
	}

	public String getMessageStatus() {
		return this.messageStatus;
	}

	public void setMessageStatus(String messageStatus) {
		this.messageStatus = messageStatus;
	}

	public Date getMessageCreateDate() {
		return this.messageCreateDate;
	}

	public void setMessageCreateDate(Date messageCreateDate) {
		this.messageCreateDate = messageCreateDate;
	}

	public Date getMessageLastUpdateDate() {
		return this.messageLastUpdateDate;
	}

	public void setMessageLastUpdateDate(Date messageLastUpdateDate) {
		this.messageLastUpdateDate = messageLastUpdateDate;
	}

}
