package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * MessageInfoId generated by hbm2java
 */
public class MessageInfoId implements java.io.Serializable {

	private int userId;
	private int messageId;

	public MessageInfoId() {
	}

	public MessageInfoId(int userId, int messageId) {
		this.userId = userId;
		this.messageId = messageId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessageInfoId))
			return false;
		MessageInfoId castOther = (MessageInfoId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getMessageId() == castOther.getMessageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getMessageId();
		return result;
	}

}
