package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * SimpleProductInfo generated by hbm2java
 */
public class SimpleProductInfo implements java.io.Serializable {

	private SimpleProductInfoId id;

	public SimpleProductInfo() {
	}

	public SimpleProductInfo(SimpleProductInfoId id) {
		this.id = id;
	}

	public SimpleProductInfoId getId() {
		return this.id;
	}

	public void setId(SimpleProductInfoId id) {
		this.id = id;
	}

}
