package com.alex.hibernate.pojo;
// Generated Dec 5, 2016 11:26:44 AM by Hibernate Tools 4.3.1.Final

/**
 * SimpleProductInfoId generated by hbm2java
 */
public class SimpleProductInfoId implements java.io.Serializable {

	private String purchaseId;
	private String brandOrder;
	private String description;
	private String subcategoryId;
	private String purchaseType;
	private Integer favoritesCount;
	private String createdAt;
	private String purchaseUrl;
	private String purchaseStatus;
	private String imageUrls;
	private String updatedAt;
	private String price;
	private String brandId;
	private String isFavorite;
	private String url;
	private String coverImageUrl;
	private String postIds;
	private String categoryId;
	private Integer editorId;
	private Integer id;
	private String name;

	public SimpleProductInfoId() {
	}

	public SimpleProductInfoId(String purchaseId, String brandOrder, String description, String subcategoryId,
			String purchaseType, Integer favoritesCount, String createdAt, String purchaseUrl, String purchaseStatus,
			String imageUrls, String updatedAt, String price, String brandId, String isFavorite, String url,
			String coverImageUrl, String postIds, String categoryId, Integer editorId, Integer id, String name) {
		this.purchaseId = purchaseId;
		this.brandOrder = brandOrder;
		this.description = description;
		this.subcategoryId = subcategoryId;
		this.purchaseType = purchaseType;
		this.favoritesCount = favoritesCount;
		this.createdAt = createdAt;
		this.purchaseUrl = purchaseUrl;
		this.purchaseStatus = purchaseStatus;
		this.imageUrls = imageUrls;
		this.updatedAt = updatedAt;
		this.price = price;
		this.brandId = brandId;
		this.isFavorite = isFavorite;
		this.url = url;
		this.coverImageUrl = coverImageUrl;
		this.postIds = postIds;
		this.categoryId = categoryId;
		this.editorId = editorId;
		this.id = id;
		this.name = name;
	}

	public String getPurchaseId() {
		return this.purchaseId;
	}

	public void setPurchaseId(String purchaseId) {
		this.purchaseId = purchaseId;
	}

	public String getBrandOrder() {
		return this.brandOrder;
	}

	public void setBrandOrder(String brandOrder) {
		this.brandOrder = brandOrder;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSubcategoryId() {
		return this.subcategoryId;
	}

	public void setSubcategoryId(String subcategoryId) {
		this.subcategoryId = subcategoryId;
	}

	public String getPurchaseType() {
		return this.purchaseType;
	}

	public void setPurchaseType(String purchaseType) {
		this.purchaseType = purchaseType;
	}

	public Integer getFavoritesCount() {
		return this.favoritesCount;
	}

	public void setFavoritesCount(Integer favoritesCount) {
		this.favoritesCount = favoritesCount;
	}

	public String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	public String getPurchaseUrl() {
		return this.purchaseUrl;
	}

	public void setPurchaseUrl(String purchaseUrl) {
		this.purchaseUrl = purchaseUrl;
	}

	public String getPurchaseStatus() {
		return this.purchaseStatus;
	}

	public void setPurchaseStatus(String purchaseStatus) {
		this.purchaseStatus = purchaseStatus;
	}

	public String getImageUrls() {
		return this.imageUrls;
	}

	public void setImageUrls(String imageUrls) {
		this.imageUrls = imageUrls;
	}

	public String getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(String updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getBrandId() {
		return this.brandId;
	}

	public void setBrandId(String brandId) {
		this.brandId = brandId;
	}

	public String getIsFavorite() {
		return this.isFavorite;
	}

	public void setIsFavorite(String isFavorite) {
		this.isFavorite = isFavorite;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCoverImageUrl() {
		return this.coverImageUrl;
	}

	public void setCoverImageUrl(String coverImageUrl) {
		this.coverImageUrl = coverImageUrl;
	}

	public String getPostIds() {
		return this.postIds;
	}

	public void setPostIds(String postIds) {
		this.postIds = postIds;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public Integer getEditorId() {
		return this.editorId;
	}

	public void setEditorId(Integer editorId) {
		this.editorId = editorId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SimpleProductInfoId))
			return false;
		SimpleProductInfoId castOther = (SimpleProductInfoId) other;

		return ((this.getPurchaseId() == castOther.getPurchaseId()) || (this.getPurchaseId() != null
				&& castOther.getPurchaseId() != null && this.getPurchaseId().equals(castOther.getPurchaseId())))
				&& ((this.getBrandOrder() == castOther.getBrandOrder()) || (this.getBrandOrder() != null
						&& castOther.getBrandOrder() != null && this.getBrandOrder().equals(castOther.getBrandOrder())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getSubcategoryId() == castOther.getSubcategoryId())
						|| (this.getSubcategoryId() != null && castOther.getSubcategoryId() != null
								&& this.getSubcategoryId().equals(castOther.getSubcategoryId())))
				&& ((this.getPurchaseType() == castOther.getPurchaseType())
						|| (this.getPurchaseType() != null && castOther.getPurchaseType() != null
								&& this.getPurchaseType().equals(castOther.getPurchaseType())))
				&& ((this.getFavoritesCount() == castOther.getFavoritesCount())
						|| (this.getFavoritesCount() != null && castOther.getFavoritesCount() != null
								&& this.getFavoritesCount().equals(castOther.getFavoritesCount())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getPurchaseUrl() == castOther.getPurchaseUrl())
						|| (this.getPurchaseUrl() != null && castOther.getPurchaseUrl() != null
								&& this.getPurchaseUrl().equals(castOther.getPurchaseUrl())))
				&& ((this.getPurchaseStatus() == castOther.getPurchaseStatus())
						|| (this.getPurchaseStatus() != null && castOther.getPurchaseStatus() != null
								&& this.getPurchaseStatus().equals(castOther.getPurchaseStatus())))
				&& ((this.getImageUrls() == castOther.getImageUrls()) || (this.getImageUrls() != null
						&& castOther.getImageUrls() != null && this.getImageUrls().equals(castOther.getImageUrls())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getPrice() == castOther.getPrice()) || (this.getPrice() != null
						&& castOther.getPrice() != null && this.getPrice().equals(castOther.getPrice())))
				&& ((this.getBrandId() == castOther.getBrandId()) || (this.getBrandId() != null
						&& castOther.getBrandId() != null && this.getBrandId().equals(castOther.getBrandId())))
				&& ((this.getIsFavorite() == castOther.getIsFavorite()) || (this.getIsFavorite() != null
						&& castOther.getIsFavorite() != null && this.getIsFavorite().equals(castOther.getIsFavorite())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null && castOther.getUrl() != null
						&& this.getUrl().equals(castOther.getUrl())))
				&& ((this.getCoverImageUrl() == castOther.getCoverImageUrl())
						|| (this.getCoverImageUrl() != null && castOther.getCoverImageUrl() != null
								&& this.getCoverImageUrl().equals(castOther.getCoverImageUrl())))
				&& ((this.getPostIds() == castOther.getPostIds()) || (this.getPostIds() != null
						&& castOther.getPostIds() != null && this.getPostIds().equals(castOther.getPostIds())))
				&& ((this.getCategoryId() == castOther.getCategoryId()) || (this.getCategoryId() != null
						&& castOther.getCategoryId() != null && this.getCategoryId().equals(castOther.getCategoryId())))
				&& ((this.getEditorId() == castOther.getEditorId()) || (this.getEditorId() != null
						&& castOther.getEditorId() != null && this.getEditorId().equals(castOther.getEditorId())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPurchaseId() == null ? 0 : this.getPurchaseId().hashCode());
		result = 37 * result + (getBrandOrder() == null ? 0 : this.getBrandOrder().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getSubcategoryId() == null ? 0 : this.getSubcategoryId().hashCode());
		result = 37 * result + (getPurchaseType() == null ? 0 : this.getPurchaseType().hashCode());
		result = 37 * result + (getFavoritesCount() == null ? 0 : this.getFavoritesCount().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getPurchaseUrl() == null ? 0 : this.getPurchaseUrl().hashCode());
		result = 37 * result + (getPurchaseStatus() == null ? 0 : this.getPurchaseStatus().hashCode());
		result = 37 * result + (getImageUrls() == null ? 0 : this.getImageUrls().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37 * result + (getBrandId() == null ? 0 : this.getBrandId().hashCode());
		result = 37 * result + (getIsFavorite() == null ? 0 : this.getIsFavorite().hashCode());
		result = 37 * result + (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result + (getCoverImageUrl() == null ? 0 : this.getCoverImageUrl().hashCode());
		result = 37 * result + (getPostIds() == null ? 0 : this.getPostIds().hashCode());
		result = 37 * result + (getCategoryId() == null ? 0 : this.getCategoryId().hashCode());
		result = 37 * result + (getEditorId() == null ? 0 : this.getEditorId().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
